name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Files
      uses: actions/checkout@main

    - name: Set up .Net Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - name: Add Nuget packages
      run: dotnet nuget add source https://nuget.pkg.github.com/nicacio11/index.json --name other -u nicacio11 -p ${{secrets.GIT_TOKEN_ADD_NUGET}} --store-password-inclear-text

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test

    - name: Create the package
      run: dotnet pack --configuration Release

    - name: Publish
      run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json